twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
when@test:
    twig:
        strict_variables: true

    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'